#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Create release

on: 
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:

    - name: Generate tag
      run: |
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")"

    - name: Create release
      uses: meeDamian/github-release@1.0
      with:
        token: ${{ secrets.OPENWRT_TOKEN }}
        body: Automatic Build | 自动编译
